### ISSUE TITLE
Story 8: Esquecer o e-mail/senha

### ISSUE THREAD

**Issue by CristinaZayra** [CristinaZayra/Grupo-1-PDS#39]
Eu como usuário queria me logar no aplicativo com meu e-mail e senha, porém acabei esquecendo a minha senha e gostaria de recupera-lá. 

**Critérios de aceitação**
* Usuário esquecer a sua senha
* Possuir campo para a recuperação do dado
* Usuário preencher seu e-mail

**Tarefas**
- [ ] Criar a interface da story
- [ ] Fazer uma consulta no banco de dados com base no e-mail que o usuário digitou
- [ ] Encaminhar e-mail para esse usuário informando a senha
- [ ] Estudar o funcionamento de como encaminhar e-mail

**Estimativa de tempo para cada tarefa**
- 2 horas
- 1 hora
- 2 horas
- 2 horas

**Comment by victor-sobreira** [comment]
https://stackoverflow.com/questions/5335273/how-to-send-an-email-using-php

**Comment by victor-sobreira** [comment]
Falta atribuir a uma Sprint.
